USE Proyecto1_Transportes_SA;
GO

/* Consultas de verificacion */

PRINT 'Tabla 1: PROFESIONES';
SELECT * FROM PROFESIONES;
GO

PRINT 'Tabla 2: EMPRESAS';
SELECT * FROM EMPRESAS;
GO

PRINT 'Tabla 3: RANGOS_SALARIALES';
SELECT * FROM RANGOS_SALARIALES;
GO

PRINT 'Tabla 4: ROLES_EMPLEADO';
SELECT * FROM ROLES_EMPLEADO;
GO

PRINT 'Tabla 5: LICENCIAS_CONDUCIR';
SELECT * FROM LICENCIAS_CONDUCIR;
GO

PRINT 'Tabla 6: ZONAS';
SELECT * FROM ZONAS;
GO

PRINT 'Tabla 7: PRECIO_BASE';
SELECT * FROM PRECIO_BASE;
GO

PRINT 'Tabla 8: ESTADO_VIAJE';
SELECT * FROM ESTADO_VIAJE;
GO

PRINT 'Tabla 9: NUMERO_UNIDAD';
SELECT * FROM NUMERO_UNIDAD;
GO

PRINT 'Tabla 10: MARCA_UNIDAD';
SELECT * FROM MARCA_UNIDAD;
GO

PRINT 'Tabla 11: MODELO_UNIDAD';
SELECT * FROM MODELO_UNIDAD;
GO

PRINT 'Tabla 12: ESTADO_UNIDAD';
SELECT * FROM ESTADO_UNIDAD;
GO

PRINT 'Tabla 13: TIPOS_AUTOBUS';
SELECT * FROM TIPOS_AUTOBUS;
GO

PRINT 'Tabla 14: ESTADO_DEKRA';
SELECT * FROM ESTADO_DEKRA;
GO

PRINT 'Tabla 15: ESTADO_MARCHAMO';
SELECT * FROM ESTADO_MARCHAMO;
GO

PRINT 'Tabla 16: ESTADO_RESERVACION';
SELECT * FROM ESTADO_RESERVACION;
GO

PRINT 'Tabla 17: DESCUENTOS';
SELECT * FROM DESCUENTOS;
GO

PRINT 'Tabla 18: ESTADO_FACTURA';
SELECT * FROM ESTADO_FACTURA;
GO

PRINT 'Tabla 19: METODOS_PAGO';
SELECT * FROM METODOS_PAGO;
GO

PRINT 'Tabla 20: ESTADO_PAGO';
SELECT * FROM ESTADO_PAGO;
GO

PRINT 'Tabla 21: CLIENTES';
SELECT * FROM CLIENTES;
GO

PRINT 'Tabla 22: EMPLEADOS';
SELECT * FROM EMPLEADOS;
GO

PRINT 'Tabla 23: RUTAS';
SELECT * FROM RUTAS;
GO

PRINT 'Tabla 24: AUTOBUSES';
SELECT * FROM AUTOBUSES;
GO

PRINT 'Tabla 25: DEKRAS';
SELECT * FROM DEKRAS;
GO

PRINT 'Tabla 26: MARCHAMOS';
SELECT * FROM MARCHAMOS;
GO

PRINT 'Tabla 27: MANTENIMIENTOS_AUTOBUS';
SELECT * FROM MANTENIMIENTOS_AUTOBUS;
GO

PRINT 'Tabla 28: VIAJES';
SELECT * FROM VIAJES;
GO

PRINT 'Tabla 29: VIAJE_PERSONAL';
SELECT * FROM VIAJE_PERSONAL;
GO

PRINT 'Tabla 30: RESERVACIONES';
SELECT * FROM RESERVACIONES;
GO

PRINT 'Tabla 31: DETALLE_RESERVACION';
SELECT * FROM DETALLE_RESERVACION;
GO

PRINT 'Tabla 32: FACTURAS';
SELECT * FROM FACTURAS;
GO

PRINT 'Tabla 33: PAGOS';
SELECT * FROM PAGOS;
GO

PRINT 'Tabla 34: BITACORA';
SELECT * FROM BITACORA;
GO
